version: 0.1
phases:
  install:
    commands:
      - "echo Downloading from GitHub"
  build:
    commands:
      - "echo Copy files to S3 bucket"
      - 'aws s3 sync . s3://tom-dane --delete --exclude ".git*"'
  post_build:
    commands:
      - "echo Clear previous version from cache"
      - 'aws cloudfront create-invalidation --distribution-id E3W3JKH6YQS9XN --paths "/*"'
artifacts:
  files:
    - "**/*"
  discard-paths: yes
