version: 0.1
phases:
  install:
    commands:
      - "echo Download from GitHub"
  build:
    commands:
      - "echo Upload to S3"
  post_build:
    commands:
      - "aws s3 cp index.html s3://tom-dane --acl public-read"
artifacts:
  files:
    - "**/*"
  discard-paths: yes
