version: 0.1
phases:
  install:
    commands:
      - "echo Downloading from GitHub"
  build:
    commands:
      - "echo Copy files to S3 bucket"
      - "aws s3 cp index.html s3://tom-dane --acl public-read"
  post_build:
    commands:
      - "echo Clear previous version from cache"
      - 'aws cloudfront create-invalidation --distribution-id E32IQDBZLB1XOB --paths /*'
artifacts:
  files:
    - "**/*"
  discard-paths: yes
