version: 2
jobs:
  deploy:
    machine:
      enabled: true
    working_directory: cd ..
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync index.html s3://tom-dane --region us-west-1'